### PR TITLE
feat(greetd): use greetd instead of sddm

### PR DESCRIPTION
**Pull request by HerrNaN**

### CODE REVIEW

**Comment by HerrNaN** [comment]
After adding `greetd`, `gtkgreet` along with a sample config for this combination from [the wiki](https://man.sr.ht/~kennylevinsen/greetd/#setting-up-greetd-with-gtkgreet) it still doesn't work.

When looking into the logs I see:
```
...
fedora greetd[1444]: error: configured default session user `greeter` is not found
...
```
Some further investigation shows me that the `greeter` user doesn't exist on the system and when trying to create it [like so](https://git.sr.ht/~kennylevinsen/greetd#manually-from-source): `sudo useradd -M -G video greeter` I get an error saying the `video` group doesn't exist either.

**Comment by HerrNaN** [comment]
I [read](https://wiki.archlinux.org/title/Users_and_groups#System_groups) that the `video` group is a pre-systemd thing and thought that could maybe explain why the system doesn't have it, so I tried adding the user without the `video` group. This got me past the previous problem but into a new one: we don't have `cage` installed on the system.

Since we will need to add `cage` for this purpose only, and it could run with `sway` instead (which we already have installed) I think we should look into running the greeter with `sway` instead.

**Comment by HerrNaN** [comment]
Seems like using `cage` or `sway` with the user setup as described above works for starting the greeter. However both suffer from the same problem when the greeter in turn wants to start the user session, dropping you into a black screen with the following error message:

`unable to set working directory: No such file or directory (os error 2)`

I am yet to find out exactly what 'file or directory' it is referring to.

**Comment by HerrNaN** [comment]
Are we running SELinux because that is known to block greetd

**Comment by williamleven** [comment]
https://www.reddit.com/r/Fedora/comments/kjyhnh/merry_christmas_and_how_to_use_greetd_in_fedora/

**Comment by williamleven** [comment]
https://github.com/ostreedev/ostree-rs-ext/issues/510

**Comment by HerrNaN** [comment]
Two ways to go here as of now:
1. Disable SELinux (tempting, but let's not throw it out as soon as it get a little windy)
2. Apply the workaround mentioned [here](https://github.com/ostreedev/ostree-rs-ext/issues/510#issuecomment-1856260605)

**Pull request merged**
